name: "Build Tauri Android App"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  build-android:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 19.8.1
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: cd frontend ; npm install ; npm fund

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup android NDK
        run: |
          sdkmanager "ndk;25.2.9519653" "platform-tools" "platforms;android-30" 
          echo 'NDK_HOME='$ANDROID_HOME'/ndk/25.2.9519653/' >> $GITHUB_ENV

      - name: Install Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt install -yqq
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb
          curl
          wget
          sdkmanager
          build-essential 
          libssl-dev 
          librsvg2-dev

      - name: Install Tauri
        run: |
          cargo install create-tauri-app
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
          cargo install tauri-cli --version "^2.0.0-alpha.10"

      - name: Build Android App
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
          RANLIB: ${{ env.NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
        run: |
          ./scripts/gen-config.sh
           cargo tauri android init
           cargo tauri android build --apk --release
           mkdir -p ./dist/android
           cp ./target/tauri/build/apk/*.apk ./dist/android/wacamoclima-${{ github.ref }}-${{ github.sha }}.apk
