name: "publish"
run-name: "Wacamorning release"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # for Arm based macs (M1 and above).
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with: 
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{secrets.TAURI_PRIVATE_KEY}}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}


      - name: Read gist
        id: gist_content
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          action: "get"
          gist_id: "fb899a610be23963ed2a33cad6a927f0"
          file_name: "wacamorning-update.json"

      # update version
            
      - name: gist update version
        id:  gist_update_version
        uses: gorgbus/edit-json-string@main
        with:
          json_string: ${{ steps.gist_content.outputs.content }}
          field: "version"
          value: "app-v__VERSION__"

      - name: Update gist version
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          action: "update"
          gist_id: "fb899a610be23963ed2a33cad6a927f0"
          file_name: "wacamorning-update.json"
          content: ${{ steps.gist_update_version.outputs.content }}

      # update notes
      - name: gist update notes
        id:  gist_update_notes
        uses: gorgbus/edit-json-string@main
        with:
          json_string: ${{ steps.gist_content.outputs.content }}
          field: "notes"
          value: "App version: app-v__VERSION__"

      - name: Update gist notes
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          action: "update"
          gist_id: "fb899a610be23963ed2a33cad6a927f0"
          file_name: "wacamorning-update.json"
          content: ${{ steps.gist_update_notes.outputs.content }}

      # update date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: gist update pub date
        id:  gist_update_pub_date
        uses: gorgbus/edit-json-string@main
        with:
          json_string: ${{ steps.gist_content.outputs.content }}
          field: "pub_date"
          value: "${{steps.date.outputs.date}}"
      
      - name: Update gist notes
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          action: "update"
          gist_id: "fb899a610be23963ed2a33cad6a927f0"
          file_name: "wacamorning-update.json"
          content: ${{ steps.gist_update_pub_date.outputs.content }}
      
